// Runway Jam levels — 18 hardcoded, deterministic Rush Hour-style layouts.
// Piece 0 is the plane (horizontal, length 2, row 2); the exit is the right
// edge of row 2. Every `minMoves` is the proven optimum (see solveBFS) and
// is verified by __tests__/runwayJamLogic.test.ts.
//
// Tiers: levels 1-4 easy (<= 8 moves), 5-8 medium, 9-12 hard (>= 12 moves),
// 13-18 expert (>= 16 moves, ascending; solver-verified via BFS search).

import type { Level } from "@/games/runway-jam/logic";

export const LEVELS: Level[] = [
  {
    id: 1,
    minMoves: 2,
    pieces: [
      { col: 0, horiz: true, id: 0, len: 2, row: 2 },
      { col: 4, horiz: false, id: 1, len: 3, row: 0 },
      { col: 1, horiz: true, id: 2, len: 2, row: 4 },
    ],
  },
  {
    id: 2,
    minMoves: 4,
    pieces: [
      { col: 2, horiz: true, id: 0, len: 2, row: 2 },
      { col: 3, horiz: true, id: 1, len: 3, row: 4 },
      { col: 1, horiz: false, id: 2, len: 2, row: 1 },
      { col: 5, horiz: false, id: 3, len: 2, row: 2 },
      { col: 4, horiz: false, id: 4, len: 3, row: 1 },
    ],
  },
  {
    id: 3,
    minMoves: 6,
    pieces: [
      { col: 0, horiz: true, id: 0, len: 2, row: 2 },
      { col: 2, horiz: false, id: 1, len: 3, row: 0 },
      { col: 3, horiz: true, id: 2, len: 3, row: 3 },
      { col: 0, horiz: true, id: 3, len: 2, row: 5 },
      { col: 5, horiz: false, id: 4, len: 3, row: 0 },
    ],
  },
  {
    id: 4,
    minMoves: 8,
    pieces: [
      { col: 0, horiz: true, id: 0, len: 2, row: 2 },
      { col: 0, horiz: false, id: 1, len: 3, row: 3 },
      { col: 4, horiz: false, id: 2, len: 2, row: 4 },
      { col: 2, horiz: true, id: 3, len: 3, row: 0 },
      { col: 2, horiz: false, id: 4, len: 2, row: 1 },
      { col: 1, horiz: true, id: 5, len: 3, row: 3 },
      { col: 5, horiz: false, id: 6, len: 2, row: 0 },
      { col: 4, horiz: true, id: 7, len: 2, row: 3 },
    ],
  },
  {
    id: 5,
    minMoves: 9,
    pieces: [
      { col: 1, horiz: true, id: 0, len: 2, row: 2 },
      { col: 3, horiz: true, id: 1, len: 3, row: 5 },
      { col: 2, horiz: false, id: 2, len: 2, row: 3 },
      { col: 3, horiz: false, id: 3, len: 3, row: 0 },
      { col: 0, horiz: false, id: 4, len: 2, row: 4 },
      { col: 5, horiz: false, id: 5, len: 3, row: 1 },
      { col: 0, horiz: false, id: 6, len: 2, row: 1 },
      { col: 3, horiz: true, id: 7, len: 2, row: 3 },
    ],
  },
  {
    id: 6,
    minMoves: 10,
    pieces: [
      { col: 0, horiz: true, id: 0, len: 2, row: 2 },
      { col: 0, horiz: false, id: 1, len: 2, row: 4 },
      { col: 5, horiz: false, id: 2, len: 2, row: 1 },
      { col: 2, horiz: true, id: 3, len: 3, row: 4 },
      { col: 4, horiz: false, id: 4, len: 3, row: 0 },
      { col: 2, horiz: false, id: 5, len: 2, row: 1 },
      { col: 1, horiz: true, id: 6, len: 3, row: 0 },
      { col: 1, horiz: false, id: 7, len: 2, row: 3 },
      { col: 4, horiz: true, id: 8, len: 2, row: 5 },
    ],
  },
  {
    id: 7,
    minMoves: 10,
    pieces: [
      { col: 0, horiz: true, id: 0, len: 2, row: 2 },
      { col: 1, horiz: true, id: 1, len: 3, row: 3 },
      { col: 4, horiz: false, id: 2, len: 2, row: 0 },
      { col: 2, horiz: false, id: 3, len: 2, row: 4 },
      { col: 5, horiz: false, id: 4, len: 2, row: 1 },
      { col: 3, horiz: true, id: 5, len: 3, row: 5 },
      { col: 1, horiz: false, id: 6, len: 2, row: 0 },
      { col: 0, horiz: false, id: 7, len: 3, row: 3 },
      { col: 3, horiz: false, id: 8, len: 3, row: 0 },
      { col: 3, horiz: true, id: 9, len: 3, row: 4 },
    ],
  },
  {
    id: 8,
    minMoves: 11,
    pieces: [
      { col: 1, horiz: true, id: 0, len: 2, row: 2 },
      { col: 1, horiz: true, id: 1, len: 2, row: 1 },
      { col: 3, horiz: false, id: 2, len: 2, row: 1 },
      { col: 3, horiz: true, id: 3, len: 3, row: 5 },
      { col: 4, horiz: true, id: 4, len: 2, row: 4 },
      { col: 1, horiz: true, id: 5, len: 2, row: 0 },
      { col: 2, horiz: false, id: 6, len: 2, row: 4 },
      { col: 4, horiz: false, id: 7, len: 3, row: 0 },
      { col: 4, horiz: true, id: 8, len: 2, row: 3 },
      { col: 0, horiz: false, id: 9, len: 3, row: 2 },
    ],
  },
  {
    id: 9,
    minMoves: 12,
    pieces: [
      { col: 1, horiz: true, id: 0, len: 2, row: 2 },
      { col: 2, horiz: true, id: 1, len: 3, row: 4 },
      { col: 1, horiz: true, id: 2, len: 2, row: 0 },
      { col: 0, horiz: true, id: 3, len: 3, row: 3 },
      { col: 5, horiz: false, id: 4, len: 3, row: 2 },
      { col: 3, horiz: false, id: 5, len: 2, row: 0 },
      { col: 3, horiz: true, id: 6, len: 3, row: 5 },
      { col: 4, horiz: true, id: 7, len: 2, row: 0 },
      { col: 3, horiz: true, id: 8, len: 2, row: 3 },
      { col: 4, horiz: false, id: 9, len: 2, row: 1 },
    ],
  },
  {
    id: 10,
    minMoves: 13,
    pieces: [
      { col: 0, horiz: true, id: 0, len: 2, row: 2 },
      { col: 2, horiz: false, id: 1, len: 3, row: 1 },
      { col: 1, horiz: false, id: 2, len: 2, row: 3 },
      { col: 4, horiz: false, id: 3, len: 2, row: 3 },
      { col: 0, horiz: false, id: 4, len: 2, row: 3 },
      { col: 1, horiz: true, id: 5, len: 3, row: 5 },
      { col: 2, horiz: true, id: 6, len: 3, row: 0 },
      { col: 0, horiz: false, id: 7, len: 2, row: 0 },
      { col: 5, horiz: false, id: 8, len: 3, row: 1 },
      { col: 2, horiz: true, id: 9, len: 2, row: 4 },
      { col: 1, horiz: false, id: 10, len: 2, row: 0 },
    ],
  },
  {
    id: 11,
    minMoves: 14,
    pieces: [
      { col: 0, horiz: true, id: 0, len: 2, row: 2 },
      { col: 1, horiz: true, id: 1, len: 2, row: 1 },
      { col: 3, horiz: true, id: 2, len: 2, row: 5 },
      { col: 0, horiz: false, id: 3, len: 2, row: 0 },
      { col: 2, horiz: false, id: 4, len: 2, row: 3 },
      { col: 5, horiz: false, id: 5, len: 3, row: 2 },
      { col: 3, horiz: true, id: 6, len: 3, row: 0 },
      { col: 3, horiz: false, id: 7, len: 2, row: 1 },
      { col: 1, horiz: false, id: 8, len: 3, row: 3 },
      { col: 1, horiz: true, id: 9, len: 2, row: 0 },
      { col: 3, horiz: true, id: 10, len: 2, row: 3 },
    ],
  },
  {
    id: 12,
    minMoves: 15,
    pieces: [
      { col: 1, horiz: true, id: 0, len: 2, row: 2 },
      { col: 5, horiz: false, id: 1, len: 3, row: 2 },
      { col: 1, horiz: true, id: 2, len: 3, row: 4 },
      { col: 5, horiz: false, id: 3, len: 2, row: 0 },
      { col: 3, horiz: true, id: 4, len: 2, row: 3 },
      { col: 0, horiz: false, id: 5, len: 3, row: 3 },
      { col: 0, horiz: true, id: 6, len: 3, row: 0 },
      { col: 3, horiz: true, id: 7, len: 2, row: 0 },
      { col: 1, horiz: true, id: 8, len: 2, row: 3 },
      { col: 4, horiz: false, id: 9, len: 2, row: 1 },
    ],
  },
  {
    id: 13,
    minMoves: 16,
    pieces: [
      { col: 2, horiz: true, id: 0, len: 2, row: 2 },
      { col: 4, horiz: true, id: 1, len: 2, row: 4 },
      { col: 0, horiz: false, id: 2, len: 3, row: 3 },
      { col: 4, horiz: false, id: 3, len: 3, row: 1 },
      { col: 4, horiz: true, id: 4, len: 2, row: 5 },
      { col: 2, horiz: true, id: 5, len: 2, row: 5 },
      { col: 1, horiz: true, id: 6, len: 2, row: 3 },
      { col: 2, horiz: true, id: 7, len: 2, row: 1 },
      { col: 5, horiz: false, id: 8, len: 3, row: 1 },
      { col: 1, horiz: false, id: 9, len: 2, row: 4 },
      { col: 0, horiz: true, id: 10, len: 2, row: 1 },
      { col: 2, horiz: true, id: 11, len: 3, row: 0 },
      { col: 3, horiz: false, id: 12, len: 2, row: 3 },
    ],
  },
  {
    id: 14,
    minMoves: 17,
    pieces: [
      { col: 1, horiz: true, id: 0, len: 2, row: 2 },
      { col: 0, horiz: false, id: 1, len: 3, row: 0 },
      { col: 1, horiz: true, id: 2, len: 3, row: 3 },
      { col: 1, horiz: true, id: 3, len: 3, row: 0 },
      { col: 4, horiz: true, id: 4, len: 2, row: 0 },
      { col: 5, horiz: false, id: 5, len: 2, row: 2 },
      { col: 3, horiz: true, id: 6, len: 2, row: 5 },
      { col: 2, horiz: true, id: 7, len: 2, row: 4 },
      { col: 5, horiz: false, id: 8, len: 2, row: 4 },
      { col: 3, horiz: false, id: 9, len: 2, row: 1 },
      { col: 4, horiz: false, id: 10, len: 2, row: 2 },
      { col: 0, horiz: false, id: 11, len: 2, row: 3 },
      { col: 1, horiz: true, id: 12, len: 2, row: 1 },
      { col: 0, horiz: true, id: 13, len: 2, row: 5 },
      { col: 4, horiz: true, id: 14, len: 2, row: 1 },
    ],
  },
  {
    id: 15,
    minMoves: 18,
    pieces: [
      { col: 0, horiz: true, id: 0, len: 2, row: 2 },
      { col: 3, horiz: true, id: 1, len: 3, row: 5 },
      { col: 5, horiz: false, id: 2, len: 2, row: 2 },
      { col: 2, horiz: true, id: 3, len: 3, row: 0 },
      { col: 2, horiz: false, id: 4, len: 2, row: 2 },
      { col: 1, horiz: true, id: 5, len: 2, row: 4 },
      { col: 5, horiz: false, id: 6, len: 2, row: 0 },
      { col: 0, horiz: false, id: 7, len: 2, row: 3 },
      { col: 3, horiz: true, id: 8, len: 2, row: 4 },
      { col: 4, horiz: false, id: 9, len: 2, row: 2 },
      { col: 0, horiz: false, id: 10, len: 2, row: 0 },
      { col: 1, horiz: true, id: 11, len: 2, row: 5 },
      { col: 2, horiz: true, id: 12, len: 3, row: 1 },
    ],
  },
  {
    id: 16,
    minMoves: 19,
    pieces: [
      { col: 2, horiz: true, id: 0, len: 2, row: 2 },
      { col: 5, horiz: false, id: 1, len: 3, row: 1 },
      { col: 2, horiz: true, id: 2, len: 3, row: 5 },
      { col: 1, horiz: true, id: 3, len: 3, row: 1 },
      { col: 1, horiz: false, id: 4, len: 2, row: 4 },
      { col: 2, horiz: false, id: 5, len: 2, row: 3 },
      { col: 4, horiz: false, id: 6, len: 3, row: 1 },
      { col: 2, horiz: true, id: 7, len: 2, row: 0 },
      { col: 0, horiz: true, id: 8, len: 2, row: 3 },
      { col: 3, horiz: true, id: 9, len: 2, row: 4 },
      { col: 4, horiz: true, id: 10, len: 2, row: 0 },
      { col: 0, horiz: false, id: 11, len: 2, row: 0 },
    ],
  },
  {
    id: 17,
    minMoves: 21,
    pieces: [
      { col: 1, horiz: true, id: 0, len: 2, row: 2 },
      { col: 5, horiz: false, id: 1, len: 2, row: 2 },
      { col: 4, horiz: false, id: 2, len: 3, row: 2 },
      { col: 2, horiz: false, id: 3, len: 3, row: 3 },
      { col: 5, horiz: false, id: 4, len: 2, row: 4 },
      { col: 3, horiz: false, id: 5, len: 3, row: 2 },
      { col: 0, horiz: false, id: 6, len: 2, row: 4 },
      { col: 0, horiz: true, id: 7, len: 3, row: 0 },
      { col: 0, horiz: false, id: 8, len: 2, row: 1 },
      { col: 4, horiz: true, id: 9, len: 2, row: 0 },
      { col: 3, horiz: true, id: 10, len: 2, row: 5 },
      { col: 4, horiz: true, id: 11, len: 2, row: 1 },
      { col: 1, horiz: false, id: 12, len: 2, row: 4 },
      { col: 1, horiz: true, id: 13, len: 3, row: 1 },
    ],
  },
  {
    id: 18,
    minMoves: 27,
    pieces: [
      { col: 0, horiz: true, id: 0, len: 2, row: 2 },
      { col: 1, horiz: true, id: 1, len: 2, row: 0 },
      { col: 2, horiz: true, id: 2, len: 3, row: 5 },
      { col: 2, horiz: false, id: 3, len: 2, row: 1 },
      { col: 3, horiz: false, id: 4, len: 2, row: 0 },
      { col: 0, horiz: true, id: 5, len: 3, row: 4 },
      { col: 5, horiz: false, id: 6, len: 2, row: 2 },
      { col: 4, horiz: false, id: 7, len: 2, row: 2 },
      { col: 4, horiz: true, id: 8, len: 2, row: 1 },
      { col: 0, horiz: false, id: 9, len: 2, row: 0 },
      { col: 2, horiz: true, id: 10, len: 2, row: 3 },
      { col: 0, horiz: true, id: 11, len: 2, row: 5 },
      { col: 4, horiz: true, id: 12, len: 2, row: 0 },
      { col: 5, horiz: false, id: 13, len: 2, row: 4 },
    ],
  },
];
