// Pure, dependency-free Word Guess logic — extracted from the component so it
// can be unit-tested (green/yellow/gray marking incl. double letters, word pool
// integrity) without pulling in React Native.

export type LetterState =
  | "correct"
  | "present"
  | "absent"
  | "empty"
  | "pending";

const AVIATION_WORDS = [
  "PILOT",
  "PLANE",
  "RADAR",
  "CABIN",
  "TOWER",
  "CARGO",
  "FLAPS",
  "CLOUD",
  "GATES",
  "ROUTE",
  "DELTA",
  "PITCH",
  "CLEAR",
  "CLIMB",
  "GLIDE",
  "HOVER",
  "ORBIT",
  "SKIES",
  "VAPOR",
  "GAUGE",
  "CHUTE",
  "SONIC",
  "BOOST",
  "WINDS",
  "FRONT",
  "NIGHT",
  "SKIDS",
  "TAXIS",
  "PYLON",
  "BRACE",
  "VISOR",
  "QUEUE",
  "TRAIL",
  "FUMES",
  "BRAKE",
  "SPEED",
  "LIGHT",
  "LAPSE",
  "STORM",
  "PROPS",
];

const COMMON_WORDS = [
  "RAISE",
  "HOUSE",
  "LIGHT",
  "PLACE",
  "STAND",
  "THINK",
  "FOUND",
  "GREAT",
  "OFTEN",
  "ABOVE",
  "EVERY",
  "THOSE",
  "STILL",
  "SINCE",
  "THREE",
  "WHILE",
  "MIGHT",
  "AFTER",
  "WATER",
  "ABOUT",
  "AGAIN",
  "WORLD",
  "NIGHT",
  "PHONE",
  "BLACK",
  "WHITE",
  "YOUNG",
  "SMALL",
  "HEART",
  "MUSIC",
  "DRIVE",
  "WRITE",
  "PAPER",
  "SHARE",
  "CHAIR",
  "SMILE",
  "FIELD",
  "DREAM",
  "BREAK",
  "CLOCK",
  "FLOOR",
  "POINT",
  "POWER",
  "BREAD",
  "EARTH",
  "GLASS",
  "GRADE",
  "GRACE",
  "PEACE",
  "PRIZE",
  "QUEEN",
  "SPACE",
  "SPARK",
  "STAGE",
  "STAKE",
  "STARE",
  "STORY",
  "STYLE",
  "SUITE",
  "SWEAR",
  "SWEET",
  "SWORD",
  "SWORE",
  "TABLE",
  "TASTE",
  "TEACH",
  "TEARS",
  "TEETH",
  "THANK",
  "THEME",
  "THICK",
  "THING",
  "THORN",
  "THOSE",
  "THROW",
  "TIGHT",
  "TIRED",
  "TODAY",
  "TOKEN",
  "TAKEN",
  "TOUGH",
  "TOWEL",
  "TRACK",
  "TRADE",
  "TRAIN",
  "TREAT",
  "TREND",
  "TRIBE",
  "TRICK",
  "TRIED",
  "BRING",
  "BUILD",
  "BUILT",
  "BURST",
  "BUYER",
  "CARGO",
  "CARRY",
  "CAUSE",
  "CEASE",
  "CEDAR",
  "CHALK",
  "CHAOS",
  "CHECK",
  "CHESS",
  "CHIEF",
  "CHILD",
  "CLAIM",
  "CLASS",
  "CLEAN",
  "CLERK",
];

// Travel, food, nature and everyday words: together the pool covers a full
// year of daily words without a repeat.
const MORE_WORDS = `
BEACH COAST OCEAN HOTEL VISIT GUIDE TOURS MONEY PASTA PIZZA LEMON MANGO GRAPE
APPLE PEACH MELON BERRY HONEY SUGAR SALAD SAUCE SPICE CREAM DRINK JUICE TOAST
BACON STEAK CANDY LUNCH SNACK FEAST RIVER LAKES TREES PLANT GRASS FLAME STONE
SHORE WAVES CORAL TIDES DUNES CLIFF RIDGE PEAKS SUNNY RAINY WINDY FROST SNOWY
MOUNT HILLS MARSH CREEK BLOOM PETAL TIGER ZEBRA HORSE SHEEP MOUSE EAGLE RAVEN
CRANE STORK GOOSE SHARK WHALE OTTER SNAIL CAMEL LLAMA PANDA KOALA BISON MOOSE
LUNAR SOLAR GLOBE ATLAS WATCH CHAIN KNIFE SPOON PLATE RADIO VIDEO PHOTO BRUSH
SHIRT SOCKS SHOES BOOTS SCARF GLOVE JEANS DRESS PURSE SHELF COUCH HAPPY QUIET
EARLY LEARN LAUGH SLEEP RELAX ENJOY REACH START BEGIN SHINE SMART BRAVE PROUD
FRESH CRISP SHARP ROUND SOLID EXTRA FINAL FIRST LARGE GIANT BRIEF QUICK RAPID
SWIFT HEAVY LUCKY MAGIC FUNNY EMPTY READY ALIVE AWAKE FOCUS SOLVE GUESS SCORE
MATCH LEVEL BONUS TIMER MONTH MAJOR MINOR NOBLE ROYAL CROWN PLAZA ALLEY VILLA
HUMAN PARTY GUEST ENTRY ANGEL AWARD BADGE BASIC BENCH BLANK BLEND BLOCK BOARD
BRAIN BRAND BRASS BRICK BROAD BROWN BUNCH CANAL CATCH CHART CHASE CHEAP CHEER
CHEST CHORD CLOSE COACH COUNT COURT COVER CRAFT CROSS CROWD CURVE CYCLE DAILY
DANCE DEPTH DIARY DOZEN DRAFT DRAMA EIGHT ELBOW EQUAL EVENT EXACT FANCY FENCE
FIFTY FLASH FLEET FLOAT FLOCK FLOUR FLUTE FORCE FORUM FRAME FRUIT GIVEN GRAIN
GRAND GREEN GROUP GUARD HABIT HEDGE HOBBY HONOR HUMOR IDEAL IMAGE INDEX INNER
IVORY JEWEL JOLLY JUDGE KNOCK LABEL LASER LAYER LIMIT LINEN LOCAL LOGIC LOYAL
MAKER MARCH METAL MODEL MOTOR MOUTH MOVIE NEVER NORTH NOVEL NURSE OFFER OLIVE
OPERA ORDER OTHER OWNER PAINT PANEL PEARL PIANO PIECE PLAIN PRESS PRICE PRIDE
PRINT PROOF QUEST QUOTE RANGE REPLY RIGHT RIVAL ROBIN ROCKY RUGBY RURAL SCALE
SCENE SEVEN SHADE SHAPE SHELL SHIFT SHORT SIGHT SKILL SLICE SLIDE SOUTH SPARE
SPEAK SPELL SPEND SPORT STAFF STAMP STEAM STEEL STICK STOVE STRAW STUDY SUPER
SWING SYRUP TITLE TOPIC TORCH TOTAL TRUCK TRUST TRUTH TULIP TWICE TWIST UNCLE
UNDER UNITY UPPER URBAN USUAL VALUE VERSE VIVID VOICE WAGON WHEAT WHEEL WHOLE
YACHT YOUTH
`
  .trim()
  .split(/\s+/);

export const WORD_POOL = [
  ...new Set([...AVIATION_WORDS, ...COMMON_WORDS, ...MORE_WORDS]),
].filter((w) => w.length === 5);

// Czech and German pools: everyday words with their native letters (the
// keyboard adds a row for them). Large enough for a year of daily words.
const CS_WORDS = `
PILOT RADAR LETEC TRASA BRÁNA KUFRY VÍZUM MOTOR VĚTER BOUŘE DRÁHA HOTEL MĚSTO
MAPKA CESTA VÝLET TAXÍK METRO LOĎKA KÁNOE TUNEL ULICE JÍZDA ODLET LÉTAT OBLAK
MĚSÍC KAPSA BATOH TAŠKA KABÁT ŠÁTEK BRÝLE ZÁMEK POTOK KOPEC ÚDOLÍ SKÁLA PÍSEK
KÁMEN TRÁVA STROM VĚTEV BLESK LEDEN DUBEN SRPEN ŘÍJEN VEČER TÝDEN KOČKA MYŠKA
KONÍK KRÁVA PRASE LIŠKA ZAJÍC JELEN SRNKA JEŽEK SOKOL HOLUB VRÁNA LABUŤ OPICE
ZEBRA PANDA KOALA MOTÝL VČELA BROUK CHLÉB MÁSLO MLÉKO VEJCE SALÁM ŠUNKA GULÁŠ
ŘÍZEK PIZZA TĚSTO MRKEV RAJČE SALÁT BANÁN OŘECH KOLÁČ KEČUP TOUST NÁPOJ LÁHEV
HRNEK TALÍŘ LŽÍCE MISKA PÁNEV HRNEC ŽIDLE SKŘÍŇ LAMPA DVEŘE STĚNA STROP MÝDLO
BUDÍK MOBIL KABEL RÁDIO KNIHA SEŠIT TUŽKA PAPÍR OBRAZ FOTKA DÁREK BALÍK PYTEL
KOŠÍK MÍČEK KARTY NŮŽKY JEHLA NITKA TRIKO SUKNĚ PÁSEK HELMA HLAVA PRSTY SRDCE
PLÍCE SVALY JAZYK VLASY BRADA LOKET BRATR STRÝC DCERA HOSTÉ HOLKA LÉKAŘ ŘIDIČ
HASIČ VOJÁK PRINC RYTÍŘ ANDĚL MALÍŘ HUDBA PÍSEŇ BUBEN PIANO ÚSMĚV SMÍCH LÁSKA
POKOJ TICHO SLOVO NÁPAD START KONEC CELEK VELKÝ NÍZKÝ TEPLÝ HORKÝ MOKRÝ SUCHÝ
ČISTÝ STARÝ MLADÝ SILNÝ SLABÝ TĚŽKÝ LEHKÝ TVRDÝ MĚKKÝ HOŘKÝ SLANÝ ČERNÝ MODRÝ
ŽLUTÝ HNĚDÝ ZLATÝ HODNÝ HEZKÝ OSTRÝ DIVNÝ JASNÝ TMAVÝ PRVNÍ DRUHÝ TŘETÍ ŠESTÝ
SEDMÝ DESET TISÍC PŮLKA BĚHAT VOLAT VIDĚT CÍTIT VĚDĚT CHTÍT MUSET DĚLAT VAŘIT
NOSIT VOZIT DÁVAT NAJÍT ČEKAT SEDĚT LEŽET VSTÁT TOČIT HÁZET LETĚT DOMOV GARÁŽ
SKLEP ŠKOLA TŘÍDA BANKA POŠTA CHATA FARMA POUŠŤ SOPKA MAJÁK KOTVA VESLO DŘEVO
NAFTA VAGÓN KOLEJ BALÓN HOKEJ TENIS ŠACHY SÁŇKY BAZÉN SAUNA PÁRTY TANEC VÝHRA
SKÓRE POHÁR ZÁVOD BARVA LINKA TEČKA ŠIPKA ČÍSLO ÚLOHA SÁZKA ŠANCE CHYBA POZOR
DOPIS KARTA VSTUP KLIMA VÝŠKA SEVER ZÁPAD LUSTR DÍVKA MATKA SVETR BUNDA ŠÁLEK
KONEV TÁCEK UBRUS ZÁVĚS HLÍNA CIHLA BETON ZLATO PLAST LÁTKA OCEÁN ODLIV LOUKA
HOUBA BŘÍZA JEDLE JAVOR PALMA LILIE ŠÍPEK KOŘEN OBILÍ SLÁMA LVICE KOBRA KRYSA
MORČE HŘÍBĚ KOZEL BERAN KRŮTA ŠTIKA LOSOS TULEŇ MOUKA PÁREK VEPŘO SUSHI KEBAB
NUDLE MANGO DATLE OLIVA KOPAT BUDIT LOVIT TAHAT LÍZAT LEPIT VÁLET JÁSAT BAVIT
TĚŠIT RANNÍ NOČNÍ DENNÍ LETNÍ ZIMNÍ JARNÍ LESNÍ POLNÍ VODNÍ VOLNÝ LEVNÝ DRAHÝ
TICHÝ CHUDÝ KRUTÝ DOBRÝ SVATÝ MĚLKÝ DRSNÝ MATNÝ HUSTÝ ZÁKON VLÁDA PRÁCE MINCE
CENÍK SLEVA NÁKUP ZBOŽÍ STROJ ŠROUB VICHR ORKÁN TEPLO CHLAD VEDRO DUSNO DATUM
PÁTEK ÚTERÝ VÝTAH PATRO ZÁBĚR VIDEO KAJAK SJEZD KAŠNA SOCHA PALÁC KAPLE LÁZNĚ
MASÁŽ RELAX
`
  .trim()
  .split(/\s+/);

const DE_WORDS = `
INSEL REISE KARTE HAFEN STADT STAND WOLKE SONNE STERN HOTEL PILOT FLUSS GLEIS
FAHRT ROUTE TISCH WAGEN KURVE PISTE MOTOR RADAR BRIEF ABEND MONAT WOCHE NACHT
TOWER START HALLE RAMPE VISUM LAGER SAUNA BUSSE METRO FOTOS ATLAS SÜDEN OSTEN
STAAT FLÜGE KLIMA MOTEL KANAL DEICH KÜSTE HÖHLE JACHT FÄHRE ANKER LOTSE RUDER
SEGEL AUTOS RÄDER MOPED DATUM APFEL BIRNE WURST NUDEL SUPPE SALAT PIZZA TORTE
HONIG SAHNE QUARK SPECK TOAST BOHNE ERBSE KRAUT LAUCH GURKE BEERE MANGO FEIGE
KAKAO MILCH SAUCE STEAK MÜSLI PASTA ESSEN GABEL TASSE KANNE LINSE OLIVE CURRY
CHILI ESSIG GRILL CREME GELEE MINZE SÄFTE TRANK KEKSE DÖNER BRÜHE SIRUP HIRSE
NÜSSE BLUME BLATT WIESE HÜGEL WELLE BUCHT PALME TANNE EICHE BIRKE LINDE TULPE
STEIN REGEN NEBEL BLITZ STURM FROST HITZE KÄLTE LICHT FEUER RAUCH TIGER ADLER
KATZE PFERD FUCHS DACHS BIBER OTTER ZEBRA KAMEL VOGEL FISCH KÄFER BIENE ROBBE
KREBS LACHS HECHT SCHAF ZIEGE TAUBE SPATZ FALKE KRÄHE MÜCKE ZWEIG SAMEN ACKER
TEICH STROM OZEAN WÜSTE KOMET BRISE HAGEL DUNST BÄUME KRAKE PANDA KOALA HYÄNE
GECKO KRÖTE AMSEL MEISE STUHL LAMPE DECKE WANNE MAUER KÜCHE VILLA HÜTTE GASSE
PLATZ MARKT LADEN KASSE MÜNZE PREIS SCHUH JACKE MÜTZE SOCKE BLUSE KLEID SCHAL
KETTE PERLE SEIFE HANDY RADIO STIFT FARBE PAKET KISTE NADEL FADEN KNOPF BESEN
EIMER NAGEL ZANGE KABEL TASTE KERZE SPÜLE REGAL TRUHE KAPPE ÄRMEL ANZUG WESTE
RÖCKE BRETT BLECH EISEN KOHLE DRAHT LASER WAAGE MAPPE TAFEL KREUZ WIEGE DIELE
KAMIN MESSE BÖRSE KONTO BELEG FEDER DAUNE WOLLE SEIDE LEDER STOFF FASER HAARE
LIPPE ZUNGE BRUST BAUCH LUNGE LEBER NIERE MAGEN SEELE STIRN WANGE HÜFTE FERSE
NARBE BEULE WUNDE SALBE PILLE VATER ONKEL TANTE NEFFE ENKEL LEUTE JUNGE GÄSTE
BAUER MALER KÖNIG PRINZ RIESE ZWERG PIRAT ENGEL CLOWN GLÜCK LIEBE TRAUM FRAGE
SPIEL PUNKT KRAFT MACHT ANGST ALTER KREIS LINIE SEITE MITTE RECHT KLANG MUSIK
KUNST BÜHNE GRUND SACHE PAUSE FEIER PARTY NOTIZ LISTE REGEL RUNDE SPORT GEIST
KRONE THRON PFEIL BOGEN SPEER LANZE GEIGE FLÖTE HARFE ORGEL PUPPE KEGEL RODEL
LOIPE FIRMA KIOSK STALL MÜHLE HECKE BODEN APRIL LESEN REDEN LEBEN GEBEN SEHEN
GEHEN HOLEN MALEN LEGEN SAGEN BAUEN HÖREN RUFEN BADEN RATEN HABEN NÄHEN HEBEN
LOBEN ATMEN HUPEN RASEN FEGEN EILEN LÖSEN WEBEN MÄHEN TOBEN WEHEN BETEN NAGEN
SÄGEN MIXEN BOXEN TAUEN KLEIN SCHÖN LEISE WEICH SAUER STARK KRANK BREIT FLACH
STEIL GLATT SPITZ BRAUN RUHIG STILL FRECH FLINK EIGEN PRIMA SUPER GENAU SANFT
KNAPP REICH FREMD EISIG STOLZ DICHT ERNST ÜBRIG HEUTE IMMER VORNE UNTEN LINKS
GERNE ETWAS ALLES VIELE WENIG SOGAR UNTER NEBEN GEGEN DURCH WEGEN SECHS ZWÖLF
`
  .trim()
  .split(/\s+/);

export type WordGuessLanguage = "cs" | "de" | "en";

const POOLS: Record<WordGuessLanguage, string[]> = {
  cs: [...new Set(CS_WORDS)],
  de: [...new Set(DE_WORDS)],
  en: WORD_POOL,
};

const QWERTZ_ROWS = [
  ["Q", "W", "E", "R", "T", "Z", "U", "I", "O", "P"],
  ["A", "S", "D", "F", "G", "H", "J", "K", "L"],
  ["ENTER", "Y", "X", "C", "V", "B", "N", "M", "⌫"],
];

const KEYBOARDS: Record<WordGuessLanguage, string[][]> = {
  cs: [
    ...QWERTZ_ROWS,
    ["Ě", "Š", "Č", "Ř", "Ž", "Ý", "Á", "Í", "É"],
    ["Ú", "Ů", "Ď", "Ť", "Ň", "Ó"],
  ],
  de: [...QWERTZ_ROWS, ["Ä", "Ö", "Ü"]],
  en: [
    ["Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P"],
    ["A", "S", "D", "F", "G", "H", "J", "K", "L"],
    ["ENTER", "Z", "X", "C", "V", "B", "N", "M", "⌫"],
  ],
};

/** Word Guess is played in Czech, German or English (fallback). */
export function wordGuessLanguage(language: string): WordGuessLanguage {
  return language === "cs" || language === "de" ? language : "en";
}

export function getWordPool(language: WordGuessLanguage): string[] {
  return POOLS[language];
}

export function getKeyboardRows(language: WordGuessLanguage): string[][] {
  return KEYBOARDS[language];
}

export function getDayOfYear(): number {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const diff = now.getTime() - start.getTime();
  return Math.floor(diff / (1000 * 60 * 60 * 24));
}

/**
 * Wordle marking. Two passes so double letters resolve correctly: greens are
 * consumed first, then each remaining letter is matched against the still-
 * unconsumed target letters. Guarantees no more yellows/greens for a letter
 * than it actually occurs in the target.
 */
export function checkGuess(guess: string, target: string): LetterState[] {
  const states: LetterState[] = new Array(5).fill("absent");
  const targetChars = target.split("");

  // Pass 1: greens
  for (let i = 0; i < 5; i += 1) {
    if (guess[i] === target[i]) {
      states[i] = "correct";
      targetChars[i] = ""; // consumed
    }
  }

  // Pass 2: yellows
  for (let i = 0; i < 5; i += 1) {
    if (states[i] === "correct") {
      continue;
    }
    const idx = targetChars.indexOf(guess[i]);
    if (idx !== -1) {
      states[i] = "present";
      targetChars[idx] = ""; // consume
    }
  }

  return states;
}

export const PRIORITY: Record<LetterState, number> = {
  absent: 1,
  correct: 3,
  empty: 0,
  pending: 0,
  present: 2,
};

export function mergeKeyboard(
  existing: Record<string, LetterState>,
  newStates: LetterState[],
  letters: string[]
): Record<string, LetterState> {
  const next = { ...existing };
  letters.forEach((letter, i) => {
    const cur = next[letter];
    const inc = newStates[i];
    if (!cur || PRIORITY[inc] > PRIORITY[cur]) {
      next[letter] = inc;
    }
  });
  return next;
}
